security:
 oauth2: resource.filter-order=3


server:
  port: 8090
#security:
#    signing-key=39I525S6VIZ2pjXh
#security.encoding-strength=256
#security.security-realm=Betman

#security.jwt.client-id=betmanclient_id
#security.jwt.client-secret=03tXJStYkqPWiqk8
#security.jwt.grant-type=password
#security.jwt.scope-read=read
#security.jwt.scope-write=write
#security.jwt.resource-ids=betmanresourceid


spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false

db:
  url:  jdbc:h2:mem:test #jdbc:postgresql://localhost:5432/betman
